### ISSUE TITLE
Arg Spec validation succesful but no tasks executed

### ISSUE THREAD

**Issue by dzintars** [Yethal/ansible-role-nushell#34]
Will leave it there as I am investigating issue of mine.
Currently i listed this role as meta dependency for my internal "nushell customization" role.
What I essentially want from this role is just to get Nushell installed without any configuration. I will do configuration from my own internal role.
ATM I have this:
```bash
TASK [yethal.nushell : Validating arguments against arg spec 'main' - Install nushell on your system] ***
ok: [workstation] => changed=false
  msg: The arg spec validation passed
  validate_args_context:
    argument_spec_name: main
    name: yethal.nushell
    path: /home/dzintars/.ansible/roles/yethal.nushell
    type: role

TASK [namespace.custom.nushell : config | Ensure config directory exist] ***********
ok: [workstation] => changed=false
  gid: 1000
  group: vagrant
  mode: '0755'
  owner: vagrant
  path: /home/vagrant/.config/nushell
  size: 53
  state: directory
  uid: 1000
  
..... and the rest of successful configuration tasks
```
As you can see, only argument spec validation task is executed.
Must admit, that this is first time i actually try to use external role. :) Usually i write all my own. :) Most likely this is the issue of mine. Just documenting it.

**Comment by Yethal** [comment]
If you want just nushell without config then set install_configs to 'none' and install_plugins to false, everything else should be fine on default

**Comment by Yethal** [comment]
@dzintars Is this still an issue on newest version or can I close this?

**Comment by dzintars** [comment]
Yes. This issue can be closed because as of now, Nushell does bring quite a lot of day-to-day pain without noticeable benefits. I just removed it. I had not tested your role since. Thank You for your effort.
